title: Los Angeles Crime Data Analysis, Devon Gorel
description: A presentation on crime data analysis
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
